server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
receipt:
  storage-path: receipts

spring:
  application:
    name: receipt-service

  datasource:
    url: jdbc:h2:mem:skiplydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          fee-service:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: basic

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  retry:
    instances:
      fee-service:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - feign.RetryableException

  circuitbreaker:
    instances:
      fee-service:
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - feign.FeignException.NotFound

  timelimiter:
    instances:
      fee-service:
        timeoutDuration: 4s